CREATE TABLE USERS (
  ID INT NOT NULL AUTO INCREMENT,
  FIRST_NAME VARCHAR (60) NOT NULL,
  LAST_NAME VARCHAR (60) NOT NULL,
  EMAIL VARCHAR (60) NOT NULL
  BIRTH_DATE DATE,
  REGISTRATION_DATE DATE NOT NULL

);