INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES ('John', 'Doe', 'johndoe@mail.ru', '2014-02-02');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES ('Anna', 'Markova', 'anna_markova@mail.ru', '2014-03-13');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES ('Charles', 'Xavier', 'charles_xavier@x-men.com', '2003-01-01');


INSERT INTO KNOWLEDGE ('')