CREATE TABLE USER (
  ID INT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR (60) NOT NULL,
  LAST_NAME VARCHAR (60) NOT NULL,
  EMAIL VARCHAR (60) NOT NULL,
  BIRTH_DATE DATE,
  REGISTRATION_DATE DATE NOT NULL,
  UNIQUE UQ_USER (EMAIL),
  PRIMARY KEY (ID),

);

CREATE TABLE KNOWLEDGE (
  ID INT NOT NULL AUTO_INCREMENT,
  DESCRIPTION VARCHAR (100) NOT NULL,
  LOCATION VARCHAR (100),
  USER_ID INT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);