INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES (1, 'John', 'Doe', 'johndoe@mail.ru', '2014-02-02');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES (2, 'Anna', 'Markova', 'anna_markova@mail.ru', '2014-03-13');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES (3, 'Charles', 'Xavier', 'charles_xavier@x-men.com', '2003-01-01');


INSERT INTO KNOWLEDGE (ID, DESCRIPTION, USER_ID) VALUES (1, 'AIbook.djvu', 1);
INSERT INTO KNOWLEDGE (ID, DESCRIPTION, USER_ID) VALUES (2, 'www.google.com', 1);
INSERT INTO KNOWLEDGE (ID, DESCRIPTION, USER_ID) VALUES (3, 'ya.ru', 1);
INSERT INTO KNOWLEDGE (ID, DESCRIPTION, USER_ID) VALUES (4, 'AIbook.pdf', 1);

INSERT INTO KNOWLEDGE (ID, DESCRIPTION, USER_ID) VALUES (11, 'local_url', 2);
INSERT INTO KNOWLEDGE (ID, DESCRIPTION, USER_ID) VALUES (12, 'spring_in_action.pdf', 1);
